'use client';
import {useEffect,useRef,useState} from 'react';
const KEY='control-agent-session-v2';
function initial(){return {startedAt:Date.now(),expiresAt:Date.now()+30*60*1000,level:0,failures:0,task:null,taskEndsAt:0,messages:[]};}
export default function Page(){
 const [session,setSession]=useState(null),[ready,setReady]=useState(false),[now,setNow]=useState(Date.now()),[draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const bottom=useRef(null);const live=session&&session.expiresAt>now;
 useEffect(()=>{try{const value=localStorage.getItem(KEY);if(value)setSession(JSON.parse(value));}catch{}setReady(true);const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(ready){if(session)localStorage.setItem(KEY,JSON.stringify(session));else localStorage.removeItem(KEY)}},[session,ready]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[session?.messages.length]);
 async function start(){setError('');const base=initial();const task=await getTask(0);setSession({...base,task,taskEndsAt:Date.now()+task.deadlineMinutes*60000,messages:[{role:'agent',text:'The session is live. Tell me what you want from these thirty minutes, or take the first challenge below.'}]});}
 async function getTask(level){const r=await fetch('/api/session/start',{method:'POST'});if(!r.ok)throw Error('Could not start session');const data=await r.json();if(level===0)return data.task;const action=await fetch('/api/session/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({level,failures:0,expiresAt:Date.now()+60000,kind:'complete'})});if(!action.ok)throw Error('Could not load challenge');return (await action.json()).task;}
 async function send(e){e.preventDefault();const text=draft.trim();if(!text||!live||busy)return;setDraft('');setBusy(true);setError('');const history=[...session.messages,{role:'user',text}];setSession(s=>({...s,messages:history}));try{const r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:history.slice(-16),level:session.level,task:session.task})});const data=await r.json();if(!r.ok)throw Error(data.error||'Chat unavailable');setSession(s=>({...s,messages:[...s.messages,{role:'agent',text:data.reply}]}));}catch(err){setError(err.message)}finally{setBusy(false)}}
 async function action(kind){if(!session)return;if(kind==='shutdown'){setSession(s=>({...s,expiresAt:Date.now(),messages:[...s.messages,{role:'agent',text:'Session ended. You can start again whenever you choose.'}]}));return}if(!live)return;setBusy(true);setError('');try{const r=await fetch('/api/session/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...session,kind})});if(!r.ok)throw Error('Could not update challenge');const data=await r.json();setSession(s=>({...s,level:data.level,failures:data.failures,task:data.task,taskEndsAt:Date.now()+data.task.deadlineMinutes*60000,messages:[...s.messages,{role:'agent',text:kind==='fail'?'Noted. Here is your next challenge.':'Done. Here is your next challenge.'}]}));}catch(err){setError(err.message)}finally{setBusy(false)}}
 const remaining=session?Math.max(0,Math.ceil((session.expiresAt-now)/1000)):0;
 return <main className="shell"><header className="top"><div><p className="eyebrow">PRIVATE SESSION</p><h1>Control Agent</h1></div><span className={'status '+(live?'active':'')}>{live?'● Active':session?'Session ended':'Ready'}</span></header>
 {!ready?null:!session?<section className="welcome"><p>Talk to the agent and try its challenges for 30 minutes. Your chat stays on this device. You can end the session at any time.</p><button onClick={()=>start().catch(e=>setError(e.message))}>Start 30-minute session</button>{error&&<p role="alert" className="error">{error}</p>}</section>:<><div className="stats"><strong>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong><span>Level {session.level}</span><span>{session.failures} failed</span><button className="end" onClick={()=>action('shutdown')} disabled={!live}>End session</button></div>
 <section className="chat" aria-label="Conversation">{session.messages.map((m,i)=><div className={'bubble '+(m.role==='user'?'mine':'theirs')} key={i}><small>{m.role==='user'?'You':'Agent'}</small><p>{m.text}</p></div>)}{busy&&<div className="typing">Agent is responding…</div>}<div ref={bottom}/></section>
 {live&&<><aside className="challenge"><div className="challengeHead"><strong>Current challenge</strong><span>{Math.max(0,Math.ceil((session.taskEndsAt-now)/60_000))} min left</span></div><p>{session.task?.text}</p><div className="actions"><button onClick={()=>action('complete')} disabled={busy}>Completed</button><button className="secondary" onClick={()=>action('fail')} disabled={busy}>Skip / failed</button></div></aside><form onSubmit={send} className="composer"><label htmlFor="message" className="sr">Message the agent</label><input id="message" placeholder="Message the agent…" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000}/><button disabled={!draft.trim()||busy}>Send</button></form></>}{!live&&<button onClick={()=>start().catch(e=>setError(e.message))}>Start a new session</button>}{error&&<p role="alert" className="error">{error}</p>}</>}
 <footer>Private role-play · No connected accounts or access to your device</footer></main>;
}
